// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int GameManager_25066ca7913364f2f9c66eac585b7269Index = 0;
		public const int Player_7704fb97ad8c64b28a3b6f9053338e64Index = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "GameManager_25066ca7913364f2f9c66eac585b7269", 0 },

			{ "Player_7704fb97ad8c64b28a3b6f9053338e64", 1 },

		};
	}
}
