// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_25066ca7913364f2f9c66eac585b7269_61fb1408_a91b_44da_90a3_08d8a9ac735d : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'GameManager' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncGameManager_id1 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private GameManager GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac_CommandTarget;		
		private GameManager GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed_CommandTarget;		
		private GameManager GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncGameManager_id1>();
			if (coherenceSync.TryGetBindingByGuid("730e0f9a-0e03-49c4-b149-ad680d0cbfac", "GameEnd", out Binding GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac))
			{
				GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac_CommandTarget = (GameManager)GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("GameManager.GameEnd", "()",
				SendCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac, ReceiveLocalCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac, MessageTarget.All, GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (GameEnd)");
			}
			if (coherenceSync.TryGetBindingByGuid("90d2cd17-de07-4dc3-a195-c28e55d09bed", "SetTime", out Binding GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed))
			{
				GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed_CommandTarget = (GameManager)GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("GameManager.SetTime", "(System.SingleUnityEngine.GameObject)",
				SendCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed, ReceiveLocalCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed, MessageTarget.All, GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SetTime)");
			}
			if (coherenceSync.TryGetBindingByGuid("5ffbb695-01f1-4793-be8f-3f05337bc655", "StartGame", out Binding GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655))
			{
				GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655_CommandTarget = (GameManager)GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("GameManager.StartGame", "()",
				SendCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655, ReceiveLocalCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655, MessageTarget.All, GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (StartGame)");
			}
			if (coherenceSync.TryGetBindingByGuid("61fb1408-a91b-44da-90a3-08d8a9ac735d", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_25066ca7913364f2f9c66eac585b7269_61fb1408_a91b_44da_90a3_08d8a9ac735d();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac(MessageTarget target, object[] args)
		{
			var command = new GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac(MessageTarget target, object[] args)
		{
			var command = new GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac();
			ReceiveCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac(command);
		}

		void ReceiveCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac(GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac command)
		{
			var target = GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac_CommandTarget;
			target.GameEnd();
		}
		void SendCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed(MessageTarget target, object[] args)
		{
			var command = new GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed();
			int i = 0;
			command.time = (float)((System.Single)args[i++]);
			command.player = (SerializeEntityID)monoBridge.UnityObjectToEntityId(args[i++] as GameObject);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed(MessageTarget target, object[] args)
		{
			var command = new GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed();
			int i = 0;
			command.time = (float)((System.Single)args[i++]);
			command.player = (SerializeEntityID)monoBridge.UnityObjectToEntityId(args[i++] as GameObject);
			ReceiveCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed(command);
		}

		void ReceiveCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed(GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed command)
		{
			var target = GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed_CommandTarget;
			target.SetTime((System.Single)(command.time),monoBridge.EntityIdToGameObject(command.player));
		}
		void SendCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655(MessageTarget target, object[] args)
		{
			var command = new GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655(MessageTarget target, object[] args)
		{
			var command = new GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655();
			ReceiveCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655(command);
		}

		void ReceiveCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655(GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655 command)
		{
			var target = GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655_CommandTarget;
			target.StartGame();
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac castedCommand:
					ReceiveCommand_GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac(castedCommand);
					break;
				case GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed castedCommand:
					ReceiveCommand_GameManager_id1_GameManager__char_46_SetTime_90d2cd17_de07_4dc3_a195_c28e55d09bed(castedCommand);
					break;
				case GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655 castedCommand:
					ReceiveCommand_GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncGameManager_id1] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
