// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using UnityEngine;
	using Coherence.Toolkit;
	using Coherence.Toolkit.Bindings;
	using Coherence.Entity;
	using Coherence.ProtocolDef;
	using Coherence.Brook;
	using Coherence.Toolkit.Bindings.ValueBindings;
	using Coherence.Toolkit.Bindings.TransformBindings;
	using Coherence.Connection;
	using Coherence.Log;
	using Logger = Coherence.Log.Logger;
	using UnityEngine.Scripting;

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_20c1e808_3e35_4fee_98a1_95a3f8cf6116 : PositionBinding
	{
		public override string CoherenceComponentName => "WorldPosition";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(coherenceSync.coherencePosition);
			set => coherenceSync.coherencePosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldPosition)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldPosition();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_1b8854bd_de4d_4423_b280_cf1aed12498d : RotationBinding
	{
		public override string CoherenceComponentName => "WorldOrientation";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(coherenceSync.coherenceRotation);
			set => coherenceSync.coherenceRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			return update.value;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (WorldOrientation)coherenceComponent;
			update.value = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new WorldOrientation();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_d32ffa6c_7b73_4411_b4f8_862c93f2f239 : BoolBinding
	{
		private UnityEngine.BoxCollider CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.BoxCollider)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.isTrigger);
			set => CastedUnityComponent.isTrigger = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816)coherenceComponent;
			return update.isTrigger;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816)coherenceComponent;
			update.isTrigger = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_79858427_6202_4bcf_aa43_0462a18a2b76 : BoolBinding
	{
		private UnityEngine.BoxCollider CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.BoxCollider)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_46ca73ea_3207_4eff_9f26_e0b06b63bf1e : BoolBinding
	{
		private UnityEngine.MeshRenderer CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.MeshRenderer)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override bool Value
		{
			get => (bool)(System.Boolean)(CastedUnityComponent.enabled);
			set => CastedUnityComponent.enabled = (System.Boolean)(value);
		}

		protected override bool ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903)coherenceComponent;
			return update.enabled;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903)coherenceComponent;
			update.enabled = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_cffa1cb1_481e_4ef9_9f7a_645e2b35e077 : DeepPositionBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Transform_6549551179320053454";

		public override uint FieldMask => 0b00000000000000000000000000000001;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localPosition);
			set => CastedUnityComponent.localPosition = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_6549551179320053454)coherenceComponent;
			return update.position;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_6549551179320053454)coherenceComponent;
			update.position = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Transform_6549551179320053454();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_45e17fea_bd00_40a3_95f8_2e79337e6965 : DeepRotationBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Transform_6549551179320053454";

		public override uint FieldMask => 0b00000000000000000000000000000010;

		public override Quaternion Value
		{
			get => (Quaternion)(UnityEngine.Quaternion)(CastedUnityComponent.localRotation);
			set => CastedUnityComponent.localRotation = (UnityEngine.Quaternion)(value);
		}

		protected override Quaternion ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_6549551179320053454)coherenceComponent;
			return update.rotation;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_6549551179320053454)coherenceComponent;
			update.rotation = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Transform_6549551179320053454();
		}
	}

	public class Binding_7704fb97ad8c64b28a3b6f9053338e64_538e6114_0057_472c_baed_45bc97daa617 : DeepScaleBinding
	{
		private UnityEngine.Transform CastedUnityComponent;		

		protected override void OnBindingCloned()
		{
			CastedUnityComponent = (UnityEngine.Transform)UnityComponent;
		}
		public override string CoherenceComponentName => "Player_id0_UnityEngine__char_46_Transform_6549551179320053454";

		public override uint FieldMask => 0b00000000000000000000000000000100;

		public override Vector3 Value
		{
			get => (Vector3)(UnityEngine.Vector3)(CastedUnityComponent.localScale);
			set => CastedUnityComponent.localScale = (UnityEngine.Vector3)(value);
		}

		protected override Vector3 ReadComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_6549551179320053454)coherenceComponent;
			return update.localScale;
		}
		
		public override ICoherenceComponentData WriteComponentData(ICoherenceComponentData coherenceComponent)
		{
			var update = (Player_id0_UnityEngine__char_46_Transform_6549551179320053454)coherenceComponent;
			update.localScale = Value;
			return update;
		}

		public override ICoherenceComponentData CreateComponentData()
		{
			return new Player_id0_UnityEngine__char_46_Transform_6549551179320053454();
		}
	}


	[Preserve]
	[AddComponentMenu("coherence/Baked/Baked 'Player' (auto assigned)")]
	[RequireComponent(typeof(CoherenceSync))]
	public class CoherenceSyncPlayer_id0 : CoherenceSyncBaked
	{
		private CoherenceSync coherenceSync;
		private Logger logger;

		// Cached targets for commands		
		private PlayerMovement Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0_CommandTarget;		
		private PlayerTimer Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab_CommandTarget;		
		private PlayerTimer Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0_CommandTarget;

		private IClient client;
		private CoherenceMonoBridge monoBridge => coherenceSync.MonoBridge;

		protected void Awake()
		{
			coherenceSync = GetComponent<CoherenceSync>();
			coherenceSync.usingReflection = false;

			logger = coherenceSync.logger.With<CoherenceSyncPlayer_id0>();
			if (coherenceSync.TryGetBindingByGuid("65889472-042b-489a-a11a-229914edd0d0", "TagPerson", out Binding Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0))
			{
				Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0_CommandTarget = (PlayerMovement)Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerMovement.TagPerson", "()",
				SendCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0, ReceiveLocalCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0, MessageTarget.All, Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (TagPerson)");
			}
			if (coherenceSync.TryGetBindingByGuid("9afdbe10-9e09-4007-8d36-d24e6e5bffab", "SetGameManagerTime", out Binding Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab))
			{
				Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab_CommandTarget = (PlayerTimer)Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerTimer.SetGameManagerTime", "()",
				SendCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab, ReceiveLocalCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab, MessageTarget.AuthorityOnly, Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SetGameManagerTime)");
			}
			if (coherenceSync.TryGetBindingByGuid("a658414d-2522-48ae-af9d-4ab558a1a4b0", "SetTime", out Binding Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0))
			{
				Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0_CommandTarget = (PlayerTimer)Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0.UnityComponent;
				coherenceSync.AddCommandRequestDelegate("PlayerTimer.SetTime", "(System.Single)",
				SendCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0, ReceiveLocalCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0, MessageTarget.AuthorityOnly, Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0_CommandTarget,false);
			}
			else
			{
				logger.Error("Couldn't find command binding (SetTime)");
			}
			if (coherenceSync.TryGetBindingByGuid("20c1e808-3e35-4fee-98a1-95a3f8cf6116", "position", out Binding InternalWorldPosition_Translation_value))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_20c1e808_3e35_4fee_98a1_95a3f8cf6116();
				InternalWorldPosition_Translation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldPosition_Translation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("1b8854bd-de4d-4423-b280-cf1aed12498d", "rotation", out Binding InternalWorldOrientation_Rotation_value))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_1b8854bd_de4d_4423_b280_cf1aed12498d();
				InternalWorldOrientation_Rotation_value.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalWorldOrientation_Rotation_value)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("d32ffa6c-7b73-4411-b4f8-862c93f2f239", "isTrigger", out Binding InternalPlayer_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_isTrigger))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_d32ffa6c_7b73_4411_b4f8_862c93f2f239();
				InternalPlayer_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_isTrigger.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_isTrigger)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.BoxCollider).isTrigger");
			}
			if (coherenceSync.TryGetBindingByGuid("79858427-6202-4bcf-aa43-0462a18a2b76", "enabled", out Binding InternalPlayer_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_enabled))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_79858427_6202_4bcf_aa43_0462a18a2b76();
				InternalPlayer_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_Player_id0_UnityEngine__char_46_BoxCollider_5711664212391567816_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.BoxCollider).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("46ca73ea-3207-4eff-9f26-e0b06b63bf1e", "enabled", out Binding InternalPlayer_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903_Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903_enabled))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_46ca73ea_3207_4eff_9f26_e0b06b63bf1e();
				InternalPlayer_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903_Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903_enabled.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903_Player_id0_UnityEngine__char_46_MeshRenderer_5546356872573735903_enabled)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.MeshRenderer).enabled");
			}
			if (coherenceSync.TryGetBindingByGuid("cffa1cb1-481e-4ef9-9f7a-645e2b35e077", "position", out Binding InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_position))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_cffa1cb1_481e_4ef9_9f7a_645e2b35e077();
				InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_position.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_position)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).position");
			}
			if (coherenceSync.TryGetBindingByGuid("45e17fea-bd00-40a3-95f8-2e79337e6965", "rotation", out Binding InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_rotation))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_45e17fea_bd00_40a3_95f8_2e79337e6965();
				InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_rotation.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_rotation)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).rotation");
			}
			if (coherenceSync.TryGetBindingByGuid("538e6114-0057-472c-baed-45bc97daa617", "localScale", out Binding InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_localScale))
			{
				var clone = new Binding_7704fb97ad8c64b28a3b6f9053338e64_538e6114_0057_472c_baed_45bc97daa617();
				InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_localScale.CloneTo(clone);
				coherenceSync.Bindings[coherenceSync.Bindings.IndexOf(InternalPlayer_id0_UnityEngine__char_46_Transform_6549551179320053454_Player_id0_UnityEngine__char_46_Transform_6549551179320053454_localScale)] = clone;
			}
			else
			{
				logger.Error("Couldn't find binding (UnityEngine.Transform).localScale");
			}
		}

		public override List<ICoherenceComponentData> CreateEntity()
		{
			if (coherenceSync.UsesLODsAtRuntime && (Archetypes.IndexForName.TryGetValue(coherenceSync.Archetype.ArchetypeName, out int archetypeIndex)))
			{
				var components = new List<ICoherenceComponentData>()
				{
					new ArchetypeComponent
					{
						index = archetypeIndex
					}
				};

				return components;
			}
			else
			{
				logger.Warning($"Unable to find archetype {coherenceSync.Archetype.ArchetypeName} in dictionary. Please, bake manually (coherence > Bake)");
			}

			return null;
		}

		public override void Initialize(CoherenceSync sync, IClient client)
		{
			if (coherenceSync == null)
			{
				coherenceSync = sync;
			}
			this.client = client;
		}
		void SendCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0();
			ReceiveCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0(command);
		}

		void ReceiveCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0(Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0 command)
		{
			var target = Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0_CommandTarget;
			target.TagPerson();
		}
		void SendCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab();
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab();
			ReceiveCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab(command);
		}

		void ReceiveCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab(Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab command)
		{
			var target = Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab_CommandTarget;
			target.SetGameManagerTime();
		}
		void SendCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0();
			int i = 0;
			command.time = (float)((System.Single)args[i++]);
			client.SendCommand(command, target, coherenceSync.EntityID);
		}

		void ReceiveLocalCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0(MessageTarget target, object[] args)
		{
			var command = new Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0();
			int i = 0;
			command.time = (float)((System.Single)args[i++]);
			ReceiveCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0(command);
		}

		void ReceiveCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0(Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0 command)
		{
			var target = Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0_CommandTarget;
			target.SetTime((System.Single)(command.time));
		}

		public override void ReceiveCommand(IEntityCommand command)
		{
			switch(command)
			{
				case Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0 castedCommand:
					ReceiveCommand_Player_id0_PlayerMovement__char_46_TagPerson_65889472_042b_489a_a11a_229914edd0d0(castedCommand);
					break;
				case Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab castedCommand:
					ReceiveCommand_Player_id0_PlayerTimer__char_46_SetGameManagerTime_9afdbe10_9e09_4007_8d36_d24e6e5bffab(castedCommand);
					break;
				case Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0 castedCommand:
					ReceiveCommand_Player_id0_PlayerTimer__char_46_SetTime_a658414d_2522_48ae_af9d_4ab558a1a4b0(castedCommand);
					break;
				default:
					logger.Warning($"[CoherenceSyncPlayer_id0] Unhandled command: {command.GetType()}.");
					break;
			}
		}
	}
}
