// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalGameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac;

		public static void Serialize(GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac Deserialize(IInProtocolBitStream bitStream)
		{

			return new GameManager_id1_GameManager__char_46_GameEnd_730e0f9a_0e03_49c4_b149_ad680d0cbfac
			(
			){};
		}
	}
}
