// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalGameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655;

		public static void Serialize(GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655 Deserialize(IInProtocolBitStream bitStream)
		{

			return new GameManager_id1_GameManager__char_46_StartGame_5ffbb695_01f1_4793_be8f_3f05337bc655
			(
			){};
		}
	}
}
