// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_id0_PlayerTimer__char_46_SetGameManagerTime_5c8c5a04_f13f_40b0_a2fe_e6d09278d417 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_id0_PlayerTimer__char_46_SetGameManagerTime_5c8c5a04_f13f_40b0_a2fe_e6d09278d417;

		public static void Serialize(Player_id0_PlayerTimer__char_46_SetGameManagerTime_5c8c5a04_f13f_40b0_a2fe_e6d09278d417 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Player_id0_PlayerTimer__char_46_SetGameManagerTime_5c8c5a04_f13f_40b0_a2fe_e6d09278d417 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Player_id0_PlayerTimer__char_46_SetGameManagerTime_5c8c5a04_f13f_40b0_a2fe_e6d09278d417
			(
			){};
		}
	}
}
