// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Player_id0_PlayerTimer__char_46_SetTime_590cc8f9_5015_4961_aee1_83f0096435b2 : IEntityCommand
	{
		public float time;

		public MessageTarget Routing => MessageTarget.AuthorityOnly;
		public uint GetComponentType() => Definition.InternalPlayer_id0_PlayerTimer__char_46_SetTime_590cc8f9_5015_4961_aee1_83f0096435b2;

		public Player_id0_PlayerTimer__char_46_SetTime_590cc8f9_5015_4961_aee1_83f0096435b2
		(
			float datatime
		)
		{
			time = datatime;
		}

		public static void Serialize(Player_id0_PlayerTimer__char_46_SetTime_590cc8f9_5015_4961_aee1_83f0096435b2 commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteFloat(commandData.time, FloatMeta.NoCompression());
		}

		public static Player_id0_PlayerTimer__char_46_SetTime_590cc8f9_5015_4961_aee1_83f0096435b2 Deserialize(IInProtocolBitStream bitStream)
		{
			var datatime = bitStream.ReadFloat(FloatMeta.NoCompression());

			return new Player_id0_PlayerTimer__char_46_SetTime_590cc8f9_5015_4961_aee1_83f0096435b2
			(
				datatime
			){};
		}
	}
}
